### ISSUE TITLE
Update Decky Frontend Lib version

### ISSUE THREAD

**Issue by jctace** [SteamGridDB/decky-steamgriddb#24]
Plugin no longer works with the latest version of decky. Per this https://github.com/SteamDeckHomebrew/decky-loader/issues/339#issuecomment-1383353181

**Comment by EnsoBrush** [comment]
I have the same problem. After entering the plugin settings I have this error:

```
TypeError: Cannot read property 'prototype' of undefined
    at eval (eval at importReactPlugin (http://localhost:1337/frontend/index.js:1874:43), <anonymous>:25864:55)
    at eval (eval at importReactPlugin (http://localhost:1337/frontend/index.js:1874:43), <anonymous>:628:20)
    at PluginLoader.importReactPlugin (http://localhost:1337/frontend/index.js:1875:30)
    at async PluginLoader.importPlugin (http://localhost:1337/frontend/index.js:1849:17)
```

**Comment by coverton341** [comment]
Same error as above. 
I'm running decky v2.4.11-pre1 
Reloading the plugin does not work nor does reinstalling. 

Rolling back to stable decky version causes the loader to fail loading on preview SteamOS.

**Comment by doZennn** [comment]
Fixed in [steam_beta_hotfix](https://github.com/SteamGridDB/decky-steamgriddb/tree/steam_beta_hotfix).  
Waiting for the Decky people to do their thing: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/193

**Comment by maddogspeighty** [comment]
What's the latest on this, I see there isn't an update yet.
